- Assets/Prefabs/Player.prefab
- Assets/Scenes/SampleScene.unity
- Assets/Scripts/PlayerMovement.cs
Added a prefab for the player.
> Small refinement of Player Movement. Added jump ability.

- Assets/Camera.meta
- Assets/Camera/Main Camera Blends.asset
- Assets/Camera/Main Camera Blends.asset.meta
- Assets/Scenes/SampleWithDollyCamera.unity
- Assets/Scenes/SampleWithDollyCamera.unity.meta
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/TagManager.asset
- UserSettings/EditorUserSettings.asset
uusi scnene jossa cinemachine dolly track
> Cinemachine track

- Assets/Materials/PlayerPhysicsMaterial.physicsMaterial2D
- Assets/Prefabs/Player.prefab
- Assets/Scenes/SampleWithDollyCamera.unity
- Assets/Scripts/PlayerMovement.cs
- ProjectSettings/Physics2DSettings.asset
Changed nearly every parameter in the player's rigidbody and movement script. Changed player's physics material too.
> Changed global 2D gravity.

- Assets/Prefabs/Camera/Main Camera.prefab
- Assets/Scripts/Player/Flashlight.cs
Removed click sound from start of scene and tuned flashlight script update-function.
> Click effect and flashlight script finetuning

- Assets/Scripts/Environment/ShadowCaster2DExtensions.cs
- ProjectSettings/EditorBuildSettings.asset
> Changed ShadowCaster2DExtensions to be build compatible. 

- Assets/Scenes/SampleWithDollyCamera.unity
- Assets/Scripts/Player/PlayerMechanics.cs
jos objectissa on jotain muuta noten lisäksi niin pelaajan pitää avata note ensiksi.
> pickable objectien twiikkaust

- Assets/Prefabs/Dynamic/ChainWithLight.prefab
- Assets/Scenes/SampleWithDollyCamera.unity
Tighter gaps between chain links so it looks more uniform.
> Chain adjustments

- Assets/Scenes/GunExplosion.unity
- Assets/Scenes/GunExplosion.unity.meta
- Assets/Scripts/JumpingSlimeAI.cs
- Assets/Scripts/Particle System/ParticleCollision.cs
Impact now sends breakables and pieces flying.
> Gun explosion

- Assets/Scenes/FirstMap.unity
Added more lights to the first map. Some ambient lighting and one glowing one for the Mörkö.
> Mörkölights

- Assets/Input.meta
- Assets/Input/InputSystem.inputsettings.asset
- Assets/Input/InputSystem.inputsettings.asset.meta
- Assets/Input/PlayerControls.cs
- Assets/Input/PlayerControls.cs.meta
- Assets/Input/PlayerControls.inputactions
- Assets/Input/PlayerControls.inputactions.meta
- Assets/Prefabs/Player/Gun.prefab
- Assets/Prefabs/Player/Player.prefab
- Assets/Scenes/FirstMap.unity
- Assets/Scenes/SampleWithDollyCamera.unity
- Assets/Scripts/CanvasManager.cs
- Assets/Scripts/FlyingEnemy.cs
- Assets/Scripts/JumpingSlimeAI.cs
- Assets/Scripts/Player/Flashlight.cs
- Assets/Scripts/Player/PlayerGun.cs
- Assets/Scripts/Player/PlayerMechanics.cs
- Assets/Scripts/Player/PlayerMovement.cs
- Assets/Scripts/Trigger.cs
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/EditorBuildSettings.asset
- ProjectSettings/ProjectSettings.asset
-Inputs are now collected in player mechanics
-player mechanics delegates functions to correct inputs at start method
> New input system

- Assets/Scripts/Player/Flashlight.cs
- Assets/Scripts/Player/PlayerGun.cs
- Assets/Scripts/Player/PlayerMechanics.cs
Player equipment had strange ownership where flashlight controlled the gun to a suspicious extent. This revision makes PlayerMechanics own and control them both.
> Flashlight and gun ownership revision

- Assets/Prefabs/Ui/UI.prefab
disables interaction with other buttons when note is open
> created ui raycast mask for notes

- Assets/Prefabs/Player/Player.prefab
- Assets/Scenes/SampleWithDollyCamera.unity
Flashlight and gun position fixed
popup text layer altered to be on top of player
> Player fixes

- Assets/Sprites/Player/Player.controller
Updated Player controller so no more errors pop up in the console
> Updated Player controller

- Assets/Animations/Player/Player.controller
- Assets/Prefabs/Player/Player.prefab
- Assets/Scripts/Player/LandAnimationStateBehaviour.cs
- Assets/Scripts/Player/PlayerMovement.cs
> Player animations

- Assets/Cutscenes/SpaceShip.playable
-Mörkölair adjusted so mörkö can move more freely in it's own lair
-Second half hub area platforming sketch added
> First map second half designing

- Assets/MorkoChaseClimbUp.cs
- Assets/MorkoChaseClimbUp.cs.meta
- Assets/Prefabs/Enemies/EnemyScriptables/MorkoEnemy.asset
- Assets/Scripts/Enemies/MorkoEnemy.cs
Mörkö now sleeps and begins to chase the player when colliding with the trigger
> Morko chase

- Assets/Scripts/Enemies/MorkoEnemy.cs
Mörkö can now climb obstacles with more efficiency
> Morko tuning

- Assets/Scripts/Enemies/MorkoEnemy.cs
> Mörkö now tries to deal damage to player.

- Assets/Animations/Player/Player_Run.anim
- Assets/Prefabs/Player/Player.prefab
The transform points are set in the animation. The movement is not snappy but rather interpolated. This leaves the light to be a little wobbly.
> Player's led light now follows the running animation.

- Assets/Prefabs/Enemies/AstarDeepDig.prefab
- Assets/Prefabs/Enemies/AstarDeepDig.prefab.meta
Flying enemies in DeepDig now have an A* prefab
Negated Z alignment on enemies
> Deep dig a star

- Assets/Prefabs/Effects/LaserLight.prefab
- Assets/Prefabs/Effects/LaserLight.prefab.meta
- Assets/Prefabs/Player/Gun.prefab
- Assets/Prefabs/Player/Player.prefab
Finetuning to gun visual effects. Normal shots now have their own particle effect and light.
> Gun effects

- Assets/Scripts/Player/SaveAndLoad.cs
Game now saves after the SpaceShipCutscene
> Space ship level status save

- Assets/Prefabs/Dynamic/Box.prefab
- Assets/Prefabs/Dynamic/ShorterChainWithLight.prefab
-Area C leftmost ledge has better design
-More lighting added to B and hub area
-Foreground adjusted so it's clearer differentiate ground from background
> First map changes

- Assets/Prefabs/Camera/Main Camera.prefab
- Assets/Prefabs/Player/Player.prefab
Reverts Tooppa/SciFiTutkimuspeli#250
> Revert "Updated AudioController"

- Assets/Prefabs/Player/Player.prefab
The bug fix is now in the player prefab.
> The bug fix in player prefab

- Assets/Scripts/Player/SaveAndLoad.cs
Fixed ship tab and new route not appearing
> Rocket scene savepoint

- Assets/Animations/Caterpillar/Caterpillar.controller
- Assets/Animations/Caterpillar/Caterpillar.controller.meta
- Assets/Prefabs/Enemies/Caterpillar.prefab
- Assets/Prefabs/Enemies/Caterpillar.prefab.meta
Caterpillar prefab created. Caterpillar now has it's own animation controller with an idle animation it enters on play.
> Caterpillar prefab

- Assets/Animations/Player/Player.controller
Changed shooting animation to trigger from any state when shooting. This way shoot animation is always used. Even when shooting while jumping or falling.
> Changed shooting animation to trigger from any state when shooting
